@startmindmap
'https://plantuml.com/mindmap-diagram
title dubbo全景图

* <&flag>架构演进
** <&globe>单一应用架构
***:所有功能合到一起
用在传统企业，升级少
;
**** 优点
**** 缺点
***** 测试成本高-要穷举所有组合情况
***** 可伸缩性差，加功能后，再走上面的测试过程
***** 可靠性差-只要有一个模块，会影响到其他模块
***** 迭代困难，版本升级很麻烦, 甩锅困难


** <&graph>RPC架构
*** 远程过程调用
****:例子
1. Thrift
2. Hessian
3. dubbo
;
***** 优点
***** 缺点
****** 服务过多，管理复杂
******: 调用次数过多
服务治理 服务注册 服务发现 服务容错
服务跟踪 服务网关 ip暴露
;
** <&pulse>SOA架构
*** 和rpc架构类似，多了服务总线ESB
**** 优点
***** 有了esb(企业服务总线)代替应用自身的事情
***** 消息路由、服务托管 mule\wso2
**** 缺点
** <&pulse>微服务架构-》一种风格
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
